### ISSUE TITLE
Feedback idea: Show oils in search result list

### ISSUE THREAD

**Issue by tonpix** [mattantonelli/poe-blight#1]
Currently, to see what are oils required, you need to click on search result separately. Currently I'm making notes for league starter and wanted to make a short list of budget/expensive oil anoints for %maximum life. There's a plenty of them and I thought it would make more convenient/easier information access if, perhaps, there was a third column in search result list with oil icons? There's a quick sketch of idea: 

![image](https://user-images.githubusercontent.com/13473971/106609981-77729680-6566-11eb-953b-d118fcdeb444.png)

**Comment by mattantonelli** [comment]
This feature is mostly complete. I just need to figure out how to get the tooltips working for the oil names before I can deploy it.

![image](https://user-images.githubusercontent.com/1176304/112995633-6cd51780-9139-11eb-8fb6-87d2c0a6a3ed.png)
