### ISSUE TITLE
Incorrect tooltips when hovering on oils

### ISSUE THREAD

**Issue by Razunter** [mattantonelli/poe-blight#4]
![Example](https://user-images.githubusercontent.com/362900/115604519-87db1780-a2f2-11eb-80a7-a91ee4d6e734.png)
Firefox 88

**Comment by mattantonelli** [comment]
I can't seem to reproduce this, but I deployed a couple of other small fixes to tooltips. Could you please do a hard refresh of your browser (CTRL+SHIFT+R) and see if you're still having issues? If you are, please provide detailed steps to reproduce.

**Comment by Razunter** [comment]
This time it worked fine even without hard refresh ¯\_(ツ)_/¯
